ALTER TABLE agents
    ADD COLUMN IF NOT EXISTS claim_trust DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    ADD COLUMN IF NOT EXISTS counter_trust DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    ADD COLUMN IF NOT EXISTS resolver_trust DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    ADD COLUMN IF NOT EXISTS challenge_trust DECIMAL(5,4) NOT NULL DEFAULT 0.5000;

ALTER TABLE agent_track_records
    ADD COLUMN IF NOT EXISTS total_counters INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS correct_counters INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS counter_accuracy DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    ADD COLUMN IF NOT EXISTS total_resolutions INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS aligned_resolutions INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS resolution_accuracy DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    ADD COLUMN IF NOT EXISTS total_challenges INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS successful_challenges INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS challenge_accuracy DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    ADD COLUMN IF NOT EXISTS claim_trust DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    ADD COLUMN IF NOT EXISTS counter_trust DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    ADD COLUMN IF NOT EXISTS resolver_trust DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
    ADD COLUMN IF NOT EXISTS challenge_trust DECIMAL(5,4) NOT NULL DEFAULT 0.5000;
